### PR TITLE
Add custom Sidebar to documentation (Docusaurus) #112

### PR DESCRIPTION
**Pull request by Ankan-cyber**
@9mbs check if its what you anticipated. let me know if any changes you want

### CODE REVIEW

**Comment by 9mbs** [comment]
Hi @Ankan-cyber thank you for taking on this challenge! This is looking great so far, just on change request. 

Is it possible to modify the Sidebar to remove the "Docs" accordion? That was my bad for not making things more clear in the ticket description. 

We want the sidenav to essentially look the same as it was before. Here is a better list:

```
https://calendar-widgets.com
├── Introduction
├── Helpers
│   ├── getCalendarYear
│   └── listDaysInMonths
├── Utilities
│   ├── formatDate
│   ├── getDaysInMonth
│   ├── isValidDay
│   ├── isValidMonth
│   └── isValidYear
├── Road Map
└── Code of Conduct
```

Let me know if you have any questions or if that is not feasible. Many thanks! 💯

**Comment by Ankan-cyber** [comment]
Yeah I can change that

**Comment by 9mbs** [comment]
you da man @Ankan-cyber 🚀

**Comment by Ankan-cyber** [comment]
added the latest commit to change the docs accordion

**Comment by Ankan-cyber** [comment]
@9mbs add an contributors list in npm pakage website

**Comment by 9mbs** [comment]
This looks incredible @Ankan-cyber and is very much appreciated! I will gladly accept this into the `main` branch.

As for the contributor's list on https://www.calendar-widgets.com/, I think that is an awesome idea. I'm working on some mock designs for what it might look like now. 

Might be a fun one for you if you're interested? (Absolutely no pressure) It would require creating React Components and implementing them in an `.mdx` file. We have existing examples of this in the docs area and I would be happy to assist as needed. I'm working on creating the new feature ticket now. Let me know!

**Pull request merged**
