### PR TITLE
#97: Updated the object-curly-spacing ESLINT rule

### PR DESCRIPTION
**Pull request by giri-madhan**
**Scope of the change:** The `object-curly-spacing` ESLINT is changed to `always`

### CODE REVIEW

**Comment by giri-madhan** [comment]
Hi! 

Please let me know if this PR is okay and needs any other changes. Thank you in advance.

(This fixes #97.)

**Comment by 9mbs** [comment]
Hi @giri-madhan thank you for grabbing this. This looks awesome! Would you mind running `pnpm run lint:fix` from the `workspaces/calendar-widgets` directory and committing the automated lint changes? I image the linter will catch a bunch of changes. Please let me know if you have any questions 🙂

**Comment by giri-madhan** [comment]
Hi @9mbs, I ran the command pnpm run lint:fix and updated this PR with the resulting changes. Could you please check them? Thank you for suggestion and help!

**Comment by 9mbs** [comment]
@giri-madhan this looks perfect, thank you!! 💯

**Comment by giri-madhan** [comment]
Thank you for your approval and merge!

**Pull request merged**
